### ISSUE TITLE
display actual number

### ISSUE THREAD

**Issue by awayand** [DrorHarari/keypirinha-ppl#1]
Hi there,
Sorry I didn't know how else to contact you. I know this project may already be dead, but allow me to ask anyway. Is there a way to display the actual number about to be called in the launcher? As it stands now, there is a main number that is displayed for the person being selected, but then when I hit tab, I see "mobile", "home", etc. entries, but don't know what numbers hide behind those designations. Outlook doesn't always sync the numbers right, so I can't trust those labels. Is there a way to "activate" such feature, or do I have to learn Python and start digging myself? Your answer is highly appreciated even if it is the latter!
Thanks a lot!

**Comment by DrorHarari** [comment]
Amazing that anyone actually got this to work...  Does it work for you? Was it easy enough to get the list?

It's not dead - I still use it. The reason why you don't have the numbers there is because of how Keypirinha works. What you are seeing there are the action names. I guess it is possible to add another non-action level to the tab navigation as a pseudo action and hitting it will activate a default action. I did not have time to look at this but will take a look when I have time.

**Comment by awayand** [comment]
oh wow thanks for the reply, didn't expect that! Actually, yes it does work, if I specify the absolute path of the file. However, I have quite an extensive directory, 2500 contacts, and it doesn't seem to index everything when I export a Google vcf, couldn't export a .vcf using Outlook. I assume the reason for the spotty indexing is some unexpected input, but it is hard for me to test and I obviously can't provide the entire file for testing to you without breaking confidentiality of personal information. Is there a debug switch I could activate to troubleshoot? F2 doesn't really show errors except when I had a typo in the config... Other than that, yes it works BEAUTIFULLY, I use it in combination with pushcuts for ios to simply dial any number directly on my iphone using this plugin, it is really magic

Edit: picture attached
![snap168](https://user-images.githubusercontent.com/1325111/106454436-15665280-64ce-11eb-9806-8d7d8ab263ca.png)

**Comment by DrorHarari** [comment]
Note that the ppl plugin contains a utility for downloading contacts from ActiveDirectory. The utility can be extractracted by copying the Ppl.keypirinha-package to ppl.zip, unzipping it and there's a etc/make_contacts.py file there. It might need to be modified a bit to made it work with the way your organization arranges its AD structure. You can use the Windows utility ADExplorer64 (from SysInternals at Microsoft) to explore you AD structure.

**Comment by awayand** [comment]
gotcha but I am not using AD, just the local OAB which is synchronized by Google Workspace Sync (formerly G Suite sync, formerly Google Apps Sync)...

**Comment by DrorHarari** [comment]
@awayand if the origin on your contacts is Google then the right way to go it to export the contacts from Google as .vcf

Can you start KP, open it (Alt+Space or your other combination) and then hit F2 to see if there was any error reported by KP?

I can add debug tracing to see how far it goes but I'll need some info. BTW, what character set are you using in the contacts (other than regular ASCII characters)?

**Comment by awayand** [comment]
@DrorHarari no errors reported other than the following:

> 
Package Ppl:
    ID       0x27ba2381
    Instance #1
             Hits         23
             CatalogItems 5
             HistoryItems 3
             KwAssocItems 8
             Keywords     8
    Plugin   Ppl.Ppl (0x27ba2381.0xb1c7ace5)
               Hits         23
               CatalogItems 5
               HistoryItems 3
               KwAssocItems 8
               Keywords     8

I should have 2500+ catalogitems, but maybe not reading it right? Also I noticed I actually may have all contacts, but I have to guess first if I should "call", "cell", "mobile", "home", otherwise if I select a contact with "call" first he/she may not show up if there is no number saved under "business" but only mobile, etc.

I am not sure how to check which character set, but sometimes there are japanese characters (hiragana, katakana, kanji) in the address or notes field...

**Comment by DrorHarari** [comment]
@awayand the data you quoted is from the Diagnostic screen (shown when pressing F3) and I was asking for anything on the Console screen (shown when pressing F2) to see there was any complaint there about Ppl.

The number of catalog items shown is based on what you selected the last time you used the plugin. The full list is kept in a memory structure and only matching items are converted into catalog items.

Anyway, now I understand your complaint about missing contacts and needing to know if to Call or Home or Cell... Yes, that's not optimal and I'll work on changing it. The original idea was that I could call Fred at home using Home->Tab->Fred and in mobile with Cell->Tab->Fred. You are correct that one may not really know which of the phone numbers is available and that's a problem.

**Comment by awayand** [comment]
Sorry about that, no complaints about ppl by pressing F2. I think it works fine, just that I have to guess the right phone number type for the  name to show up. Ideally would love to type name -> pick number (whether it is labeled home or business or whatever is secondary, as I can usually recognize the number and the labels always get jumbled up no matter how careful I am anyway)...

**Comment by DrorHarari** [comment]
Try this pre-release and let me know if it works better:
https://github.com/DrorHarari/keypirinha-ppl/releases/tag/v0.7

**Comment by awayand** [comment]
works great, thanks a lot! I can see the numbers, but still have to guess first which field is being used. I'd rather just type the name and be presented with all numbers available to call. Looks great though, it's a real improvement and time saver!

**Comment by DrorHarari** [comment]
Just type `call <tab> name` and select the number you wish to call. You would use the specific number type first if you know there are several numbers and want to pre-select one (like using `cell <tab> name <enter>`)

**Comment by awayand** [comment]
Oh I see, I didn't try the <tab> key. Looks absolutely PERFECT now, love it!!! Thanks so much.

**Comment by DrorHarari** [comment]
Closing and releasing for whomever else uses it....
