### ISSUE TITLE
vcard file format

### ISSUE THREAD

**Issue by Nikostratos** [DrorHarari/keypirinha-ppl#3]
I encoutered two issues with importing vcards:

**1. vcard file format has to be given in one syntax:**

e.g. Phone-Numbers have to be in format TEL;TYPE=CELL:

However some vcards are in Format:
TEL;WORK;VOICE:
TEL;CELL;VOICE:

(As exported from MS Outlook, vcard-version 2.1)
=> If implementation is too much trouble for now, then maybe this should be documented?

**2. vcard encoding**

When importing vcard I got the error "can't decode 0xcf"
I see that kp.ppl is expecting utf-8
However MS Outlook exports vcards in format:
ORG;CHARSET=Windows-1252:Rüdiger Engineering
ADR;WORK;CHARSET=Windows1252:;;Feldstraße 105

manually removing "ü" from vcard solves the issue and exports successfully.
=> Is there a way to skip characters, which cannot be decoded?
For this particular case "ü" and "ß" don't need to be imported...

**Comment by DrorHarari** [comment]
Hi Nikostratos. 

I have added support for different encoding - check the new encoding parameter in the ppl.ini file for how to specify the encoding.

Also added support for customizing the VCARD format - check the cell_tag, home_tag and work_tag in the ppl.ini file.

Currently the release is in preview - please download version 0.8 and let me know if it works for you.

/d

**Comment by Nikostratos** [comment]
wow - that was fast!
Great.
will have a look and get back.

Thanks.

**Comment by Nikostratos** [comment]
Amazing.
it's working 100%.

I like the solution with the ppl.ini - config file.
